// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVi1AOWAyZ5Rg_H0-96zfS_juWIn62ohY',
    appId: '1:1023933723224:web:a69a6c487bc3f98829902d',
    messagingSenderId: '1023933723224',
    projectId: 'instaclone-16cf4',
    authDomain: 'instaclone-16cf4.firebaseapp.com',
    storageBucket: 'instaclone-16cf4.firebasestorage.app',
    measurementId: 'G-444J5QNVG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iAlL64MXr1ZQXgF3hHV161ND3NSguZ8',
    appId: '1:1023933723224:android:526213baf040d0de29902d',
    messagingSenderId: '1023933723224',
    projectId: 'instaclone-16cf4',
    storageBucket: 'instaclone-16cf4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzV4G9Ie2oucVKcTgv-ujQuqJKCHsPor0',
    appId: '1:1023933723224:ios:14e976fe68ff9ac329902d',
    messagingSenderId: '1023933723224',
    projectId: 'instaclone-16cf4',
    storageBucket: 'instaclone-16cf4.firebasestorage.app',
    iosBundleId: 'com.example.alab',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzV4G9Ie2oucVKcTgv-ujQuqJKCHsPor0',
    appId: '1:1023933723224:ios:14e976fe68ff9ac329902d',
    messagingSenderId: '1023933723224',
    projectId: 'instaclone-16cf4',
    storageBucket: 'instaclone-16cf4.firebasestorage.app',
    iosBundleId: 'com.example.alab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVi1AOWAyZ5Rg_H0-96zfS_juWIn62ohY',
    appId: '1:1023933723224:web:e104dc5d5864f6f729902d',
    messagingSenderId: '1023933723224',
    projectId: 'instaclone-16cf4',
    authDomain: 'instaclone-16cf4.firebaseapp.com',
    storageBucket: 'instaclone-16cf4.firebasestorage.app',
    measurementId: 'G-F2FW9XCMMR',
  );
}
