// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjDhid_XyPNY93im0-mpMkDweoea0beaU',
    appId: '1:469642209178:web:d51278b36507907834bc23',
    messagingSenderId: '469642209178',
    projectId: 'alab-ebc7c',
    authDomain: 'alab-ebc7c.firebaseapp.com',
    storageBucket: 'alab-ebc7c.firebasestorage.app',
    measurementId: 'G-94THY1PVFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvM6M4QYH2L_oqWenF2ly1Sep4akTBdf8',
    appId: '1:469642209178:android:725c060f197263e334bc23',
    messagingSenderId: '469642209178',
    projectId: 'alab-ebc7c',
    storageBucket: 'alab-ebc7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQb29WgmCK5NCxAdQC_UiFtY-nvkq0Y8',
    appId: '1:469642209178:ios:0d5b5b36291a8ba134bc23',
    messagingSenderId: '469642209178',
    projectId: 'alab-ebc7c',
    storageBucket: 'alab-ebc7c.firebasestorage.app',
    iosBundleId: 'com.example.alab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQb29WgmCK5NCxAdQC_UiFtY-nvkq0Y8',
    appId: '1:469642209178:ios:0d5b5b36291a8ba134bc23',
    messagingSenderId: '469642209178',
    projectId: 'alab-ebc7c',
    storageBucket: 'alab-ebc7c.firebasestorage.app',
    iosBundleId: 'com.example.alab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjDhid_XyPNY93im0-mpMkDweoea0beaU',
    appId: '1:469642209178:web:117b9c369f0e703434bc23',
    messagingSenderId: '469642209178',
    projectId: 'alab-ebc7c',
    authDomain: 'alab-ebc7c.firebaseapp.com',
    storageBucket: 'alab-ebc7c.firebasestorage.app',
    measurementId: 'G-ZWJMCQ800X',
  );
}
